/* eslint-disable */
import { z } from 'zod';

export const BeneficiaryServiceScalarFieldEnumSchema = z.enum([
    'id',
    'createdAt',
    'updatedAt',
    'isPublished',
    'isSoftDeleted',
    'createdById',
    'updatedById',
    'isActive',
    'deactivationReason',
    'deactivationDate',
    'name',
    'Note',
    'billedAmmount',
    'allowedAmmount',
    'copayAmmount',
    'cashAmount',
    'coveredAmount',
    'defferedAmount',
    'coinsuranceAmount',
    'notes',
    'isExamination',
    'groupId',
    'reviewStatusId',
    'entryRecordId',
    'medicalServiceId',
]);
