import cuid2 from "@paralleldrive/cuid2";
import { SeedHelper } from "../scripts/generateSeederFiles";
import { ar, en } from "@faker-js/faker";

export const Gender = [
  {
    ...SeedHelper.functions.fakeGender(),
    // id: cuid2.createId(),
    name: "Unknown",
    english: "Unknown",
    arabic: "غير معروف",
  },
  {
    ...SeedHelper.functions.fakeGender(),
    // id: cuid2.createId(),
    name: "female",
    english: "female",
    arabic: "أنثى",
  },
  {
    ...SeedHelper.functions.fakeGender(),
    // id: cuid2.createId(),
    name: "male",
    english: "male",
    arabic: "ذكر",
  },
];

export const TenantType = [
  {
    ...SeedHelper.functions.fakeTenantType(),
    id: cuid2.createId(),
    name: "institution",
    english: "institution",
    arabic: "مؤسسة",
  },
  {
    ...SeedHelper.functions.fakeTenantType(),
    id: cuid2.createId(),
    name: "medical",
    english: "medical",
    arabic: "طبي",
  },
  {
    ...SeedHelper.functions.fakeTenantType(),
    id: cuid2.createId(),
    name: "personal",
    english: "personal",
    arabic: "شخصي",
  },
];

export const Role = [
  {
    ...SeedHelper.functions.fakeRole(),
    id: cuid2.createId(),
    name: "owner",
    english: "owner",
    arabic: "مالك",
  },
  {
    ...SeedHelper.functions.fakeRole(),
    id: cuid2.createId(),
    name: "admin",
    english: "admin",
    arabic: "مدير",
  },
  {
    ...SeedHelper.functions.fakeRole(),
    id: cuid2.createId(),
    name: "member",
    english: "member",
    arabic: "عضو",
  },
  {
    ...SeedHelper.functions.fakeRole(),
    id: cuid2.createId(),
    name: "guest",
    english: "guest",
    arabic: "زائر",
  },
  {
    ...SeedHelper.functions.fakeRole(),
    id: cuid2.createId(),
    name: "supervisor",
    english: "supervisor",
    arabic: "مشرف",
  },
  {
    ...SeedHelper.functions.fakeRole(),
    id: cuid2.createId(),
    name: "other",
    english: "other",
    arabic: "اخرى",
  },
];

export const DeviceType = [
  {
    ...SeedHelper.functions.fakeDeviceType(),
    id: cuid2.createId(),
    name: "android",
    english: "android",
    arabic: "اندريود",
  },
  {
    ...SeedHelper.functions.fakeDeviceType(),
    id: cuid2.createId(),
    name: "ios",
    english: "ios",
    arabic: "إي.او.اس",
  },
  {
    ...SeedHelper.functions.fakeDeviceType(),
    id: cuid2.createId(),
    name: "web",
    english: "web",
    arabic: "متصفح",
  },
  {
    ...SeedHelper.functions.fakeDeviceType(),
    id: cuid2.createId(),
    name: "other",
    english: "other",
    arabic: "اخرى",
  },
];

export const Relationship = [
  {
    ...SeedHelper.functions.fakeRelationship(),
    id: cuid2.createId(),
    name: "self",
    english: "self",
    arabic: "نفسه",
  },
  {
    ...SeedHelper.functions.fakeRelationship(),
    id: cuid2.createId(),
    name: "father",
    english: "father",
    arabic: "الوالد",
  },
  {
    ...SeedHelper.functions.fakeRelationship(),
    id: cuid2.createId(),
    name: "mother",
    english: "mother",
    arabic: "الوالده",
  },
  {
    ...SeedHelper.functions.fakeRelationship(),
    id: cuid2.createId(),
    name: "husband",
    english: "husband",
    arabic: "الزوج",
  },
  {
    ...SeedHelper.functions.fakeRelationship(),
    id: cuid2.createId(),
    name: "wife",
    english: "wife",
    arabic: "الزوجه",
  },
  {
    ...SeedHelper.functions.fakeRelationship(),
    id: cuid2.createId(),
    name: "son",
    english: "son",
    arabic: "الإبن",
  },
  {
    ...SeedHelper.functions.fakeRelationship(),
    id: cuid2.createId(),
    name: "daughter",
    english: "daughter",
    arabic: "الإبنه",
  },
  {
    ...SeedHelper.functions.fakeRelationship(),
    id: cuid2.createId(),
    name: "brother",
    english: "brother",
    arabic: "الأخ",
  },
  {
    ...SeedHelper.functions.fakeRelationship(),
    id: cuid2.createId(),
    name: "sister",
    english: "sister",
    arabic: "الأخت",
  },
  {
    ...SeedHelper.functions.fakeRelationship(),
    id: cuid2.createId(),
    name: "uncle",
    english: "uncle",
    arabic: "العم",
  },
  {
    ...SeedHelper.functions.fakeRelationship(),
    id: cuid2.createId(),
    name: "aunt",
    english: "aunt",
    arabic: "العمة",
  },
  {
    ...SeedHelper.functions.fakeRelationship(),
    id: cuid2.createId(),
    name: "grandfather",
    english: "grandfather",
    arabic: "الحد",
  },
  {
    ...SeedHelper.functions.fakeRelationship(),
    id: cuid2.createId(),
    name: "grandmother",
    english: "grandmother",
    arabic: "الجدة",
  },
  {
    ...SeedHelper.functions.fakeRelationship(),
    id: cuid2.createId(),
    name: "other",
    english: "other",
    arabic: "آخر",
  },
];

export const FingerType = [
  {
    ...SeedHelper.functions.fakeFingerType(),
    id: cuid2.createId(),
    name: "leftthumb",
    english: "left thumb",
    arabic: "إبهام اليد اليسرى",
  },
  {
    ...SeedHelper.functions.fakeFingerType(),
    id: cuid2.createId(),
    name: "leftindex",
    english: "left index",
    arabic: "سبابة اليد اليسرى",
  },
  {
    ...SeedHelper.functions.fakeFingerType(),
    id: cuid2.createId(),
    name: "leftmiddle",
    english: "left middle",
    arabic: "وسط اليد اليسرى",
  },
  {
    ...SeedHelper.functions.fakeFingerType(),
    id: cuid2.createId(),
    name: "leftring",
    english: "left ring",
    arabic: "خاتم اليد اليسرى",
  },
  {
    ...SeedHelper.functions.fakeFingerType(),
    id: cuid2.createId(),
    name: "leftlittle",
    english: "left little",
    arabic: "اليد اليسرى الصغيرة",
  },
  {
    ...SeedHelper.functions.fakeFingerType(),
    id: cuid2.createId(),
    name: "rightthumb",
    english: "right thumb",
    arabic: "إبهام اليد اليمنى",
  },
  {
    ...SeedHelper.functions.fakeFingerType(),
    id: cuid2.createId(),
    name: "rightindex",
    english: "right index",
    arabic: "سبابة اليد اليمنى",
  },
  {
    ...SeedHelper.functions.fakeFingerType(),
    id: cuid2.createId(),
    name: "rightmiddle",
    english: "right middle",
    arabic: "وسط اليد اليمنى",
  },
  {
    ...SeedHelper.functions.fakeFingerType(),
    id: cuid2.createId(),
    name: "rightring",
    english: "right ring",
    arabic: "خاتم اليد اليمنى",
  },
  {
    ...SeedHelper.functions.fakeFingerType(),
    id: cuid2.createId(),
    name: "rightlittle",
    english: "right little",
    arabic: "اليد اليمنى الصغيرة",
  },
  {
    ...SeedHelper.functions.fakeFingerType(),
    id: cuid2.createId(),
    name: "unkown",
    english: "unkown",
    arabic: "مجهول",
  },
];

export const Currency = [
  {
    ...SeedHelper.functions.fakeCurrency(),
    id: cuid2.createId(),
    name: "Libyan Dinars",
    english: "Libyan Dinars",
    arabic: "دينار ليبي",
    code: "LYD",
    symbol: "LD",
    buyExchangeRate: 1,
    sellExchangeRate: 1,
  },
  {
    ...SeedHelper.functions.fakeCurrency(),
    id: cuid2.createId(),
    name: "US Dollar",
    english: "US Dollar",
    arabic: "دولار أمريكي",
    code: "USD",
    symbol: "$",
    buyExchangeRate: 1.2,
    sellExchangeRate: 1.23,
  },
  {
    ...SeedHelper.functions.fakeCurrency(),
    id: cuid2.createId(),
    name: "Euro",
    english: "Euro",
    arabic: "يورو",
    code: "EUR",
    symbol: "€",
    buyExchangeRate: 0.85,
    sellExchangeRate: 0.86,
  },
  {
    ...SeedHelper.functions.fakeCurrency(),
    id: cuid2.createId(),
    name: "British Pound",
    english: "British Pound",
    arabic: "جنيه إسترليني",
    code: "GBP",
    symbol: "£",
    buyExchangeRate: 0.72,
    sellExchangeRate: 0.73,
  },
  {
    ...SeedHelper.functions.fakeCurrency(),
    id: cuid2.createId(),
    name: "Japanese Yen",
    english: "Japanese Yen",
    arabic: "ين ياباني",
    code: "JPY",
    symbol: "¥",
    buyExchangeRate: 110.0,
    sellExchangeRate: 111.0,
  },
  {
    ...SeedHelper.functions.fakeCurrency(),
    id: cuid2.createId(),
    name: "Australian Dollar",
    english: "Australian Dollar",
    arabic: "دولار أسترالي",
    code: "AUD",
    symbol: "A$",
    buyExchangeRate: 1.3,
    sellExchangeRate: 1.31,
  },
];

export const ReviewStatus = [
  {
    ...SeedHelper.functions.fakeReviewStatus(),
    name: "pending",
    english: "Pending",
    arabic: "إنتظار التأكيد",
  },
  {
    ...SeedHelper.functions.fakeReviewStatus(),
    name: "approved",
    english: "Approved",
    arabic: "تم التأكيد",
  },
  {
    ...SeedHelper.functions.fakeReviewStatus(),
    name: "rejected",
    english: "Rejected",
    arabic: "مرفوض",
  },
  {
    ...SeedHelper.functions.fakeReviewStatus(),
    name: "under_review",
    english: "Under Review",
    arabic: "قيد المراجعة",
  },
  {
    ...SeedHelper.functions.fakeReviewStatus(),
    name: "resolved",
    english: "Resolved",
    arabic: "تم الحل",
  },
  {
    ...SeedHelper.functions.fakeReviewStatus(),
    name: "escalated",
    english: "Escalated",
    arabic: "تصعيد",
  },
  {
    ...SeedHelper.functions.fakeReviewStatus(),
    name: "in_progress",
    english: "In Progress",
    arabic: "جاري العمل",
  },
  {
    ...SeedHelper.functions.fakeReviewStatus(),
    name: "on_hold",
    english: "On Hold",
    arabic: "معلق",
  },
  {
    ...SeedHelper.functions.fakeReviewStatus(),
    name: "withdrawn",
    english: "Withdrawn",
    arabic: "تم السحب",
  },
  {
    ...SeedHelper.functions.fakeReviewStatus(),
    name: "reopened",
    english: "Reopened",
    arabic: "تم إعادة الفتح",
  },
];

export const Country = [
  {
    ...SeedHelper.functions.fakeCountry(),
    name: "libya",
    english: "Libya",
    arabic: "ليبيا",
    code: "LY",
  },
];
