import { userRouter } from './cruds/user.router';
import { tenantMemberRouter } from './cruds/tenantMember.router';
import { tenantRouter } from './cruds/tenant.router';
import { deviceTokenRouter } from './cruds/deviceToken.router';
import { institutionRouter } from './cruds/institution.router';
import { beneficiaryEntityRouter } from './cruds/beneficiaryEntity.router';
import { beneficiaryEntityFutureStatusChangeRouter } from './cruds/beneficiaryEntityFutureStatusChange.router';
import { beneficiaryRouter } from './cruds/beneficiary.router';
import { beneficiaryFutureStatusChangeRouter } from './cruds/beneficiaryFutureStatusChange.router';
import { institutionMedicalServiceRouter } from './cruds/institutionMedicalService.router';
import { fingerprintBiometricRouter } from './cruds/fingerprintBiometric.router';
import { iDCardRouter } from './cruds/iDCard.router';
import { faceBiometricRouter } from './cruds/faceBiometric.router';
import { voiceBiometricRouter } from './cruds/voiceBiometric.router';
import { insurancePolicyRouter } from './cruds/insurancePolicy.router';
import { benefitPackageRouter } from './cruds/benefitPackage.router';
import { insurancePolicyMedicalCenterRouter } from './cruds/insurancePolicyMedicalCenter.router';
import { medicalCenterRouter } from './cruds/medicalCenter.router';
import { benefitPackageMedicalServiceCategoryRouter } from './cruds/benefitPackageMedicalServiceCategory.router';
import { medicalServiceCategoryRouter } from './cruds/medicalServiceCategory.router';
import { medicalServiceRouter } from './cruds/medicalService.router';
import { entryRecordRouter } from './cruds/entryRecord.router';
import { beneficiaryServiceRouter } from './cruds/beneficiaryService.router';
import { reviewStatusRouter } from './cruds/reviewStatus.router';
import { beneficiaryBalanceRouter } from './cruds/beneficiaryBalance.router';
import { diagnosisAttachmentRouter } from './cruds/diagnosisAttachment.router';
import { labReportAttachmentRouter } from './cruds/labReportAttachment.router';
import { prescriptionAttachmentRouter } from './cruds/prescriptionAttachment.router';
import { reviewStatusEnumRouter } from './cruds/reviewStatusEnum.router';
import { genderEnumRouter } from './cruds/genderEnum.router';
import { currencyEnumRouter } from './cruds/currencyEnum.router';
import { relationshipEnumRouter } from './cruds/relationshipEnum.router';
import { tenantTypeEnumRouter } from './cruds/tenantTypeEnum.router';
import { roleEnumRouter } from './cruds/roleEnum.router';
import { deviceTypeEnumRouter } from './cruds/deviceTypeEnum.router';
import { fingerTypeEnumRouter } from './cruds/fingerTypeEnum.router';
import { cityEnumRouter } from './cruds/cityEnum.router';
import { countryEnumRouter } from './cruds/countryEnum.router';
import { Router } from "express";
export const crudRouter = Router();


crudRouter.use("/user", userRouter );
crudRouter.use("/tenantMember", tenantMemberRouter );
crudRouter.use("/tenant", tenantRouter );
crudRouter.use("/deviceToken", deviceTokenRouter );
crudRouter.use("/institution", institutionRouter );
crudRouter.use("/beneficiaryEntity", beneficiaryEntityRouter );
crudRouter.use("/beneficiaryEntityFutureStatusChange", beneficiaryEntityFutureStatusChangeRouter );
crudRouter.use("/beneficiary", beneficiaryRouter );
crudRouter.use("/beneficiaryFutureStatusChange", beneficiaryFutureStatusChangeRouter );
crudRouter.use("/institutionMedicalService", institutionMedicalServiceRouter );
crudRouter.use("/fingerprintBiometric", fingerprintBiometricRouter );
crudRouter.use("/iDCard", iDCardRouter );
crudRouter.use("/faceBiometric", faceBiometricRouter );
crudRouter.use("/voiceBiometric", voiceBiometricRouter );
crudRouter.use("/insurancePolicy", insurancePolicyRouter );
crudRouter.use("/benefitPackage", benefitPackageRouter );
crudRouter.use("/insurancePolicyMedicalCenter", insurancePolicyMedicalCenterRouter );
crudRouter.use("/medicalCenter", medicalCenterRouter );
crudRouter.use("/benefitPackageMedicalServiceCategory", benefitPackageMedicalServiceCategoryRouter );
crudRouter.use("/medicalServiceCategory", medicalServiceCategoryRouter );
crudRouter.use("/medicalService", medicalServiceRouter );
crudRouter.use("/entryRecord", entryRecordRouter );
crudRouter.use("/beneficiaryService", beneficiaryServiceRouter );
crudRouter.use("/reviewStatus", reviewStatusRouter );
crudRouter.use("/beneficiaryBalance", beneficiaryBalanceRouter );
crudRouter.use("/diagnosisAttachment", diagnosisAttachmentRouter );
crudRouter.use("/labReportAttachment", labReportAttachmentRouter );
crudRouter.use("/prescriptionAttachment", prescriptionAttachmentRouter );
crudRouter.use("/reviewStatusEnum", reviewStatusEnumRouter );
crudRouter.use("/genderEnum", genderEnumRouter );
crudRouter.use("/currencyEnum", currencyEnumRouter );
crudRouter.use("/relationshipEnum", relationshipEnumRouter );
crudRouter.use("/tenantTypeEnum", tenantTypeEnumRouter );
crudRouter.use("/roleEnum", roleEnumRouter );
crudRouter.use("/deviceTypeEnum", deviceTypeEnumRouter );
crudRouter.use("/fingerTypeEnum", fingerTypeEnumRouter );
crudRouter.use("/cityEnum", cityEnumRouter );
crudRouter.use("/countryEnum", countryEnumRouter );
