import { z } from 'zod';

export const InstitutionScalarFieldEnumSchema = z.enum([
  'id',
  'createdAt',
  'updatedAt',
  'isPublished',
  'isSoftDeleted',
  'isActive',
  'deactivationReason',
  'deactivationDate',
  'name',
  'code',
  'legacyCode',
  'description',
  'cityHQ',
  'address',
  'phoneArray',
  'emailArray',
  'website',
  'facebookLink',
  'googleMapsLink',
  'twitterLink',
  'instagramLink',
  'latitude',
  'longitude',
]);
